server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/stock-users
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:kafka:9092}
      group-id: group-02
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

