services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ekart-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - ekart-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ekart-network

  serviceregistry:
    image: serviceregistry:v1.0
    container_name: serviceregistry
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - ekart-network

  configserver:
    image: configserver:v1.0
    container_name: configserver
    restart: unless-stopped
    depends_on:
      - serviceregistry
    environment:
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
    ports:
      - "9296:9296"
    networks:
      - ekart-network

  userservice:
    image: userservice:v1.0
    container_name: userservice
    restart: unless-stopped
    depends_on:
      - mysql
      - kafka
      - configserver
    environment:
      DB_HOST: mysql
      CONFIG_SERVER_URL: http://configserver:9296
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      KAFKA_SERVER: kafka:9092
    ports:
      - "8084:8084"
    networks:
      - ekart-network

  stockservice:
    image: stockservice:v1.0
    container_name: stockservice
    restart: unless-stopped
    depends_on:
      - mysql
      - configserver
    environment:
      DB_HOST: mysql
      CONFIG_SERVER_URL: http://configserver:9296
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - ekart-network

  orderservice:
    image: orderservice:v1.0
    container_name: orderservice
    restart: unless-stopped
    depends_on:
      - mysql
      - configserver
    environment:
      DB_HOST: mysql
      CONFIG_SERVER_URL: http://configserver:9296
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - ekart-network

  paymentservice:
    image: paymentservice:v1.0
    container_name: paymentservice
    restart: unless-stopped
    depends_on:
      - mysql
      - configserver
    environment:
      DB_HOST: mysql
      CONFIG_SERVER_URL: http://configserver:9296
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
    ports:
      - "8082:8082"
    networks:
      - ekart-network

  frontendservice:
    image: frontendservice:v1.0
    container_name: frontendservice
    restart: unless-stopped
    depends_on:
      - kafka
      - configserver
    environment:
      CONFIG_SERVER_URL: http://configserver:9296
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
      KAFKA_SERVER: kafka:9092
    ports:
      - "8086:8086"
    networks:
      - ekart-network

  apigateway:
    image: apigateway:v1.0
    container_name: apigateway
    restart: unless-stopped
    depends_on:
      - configserver
    environment:
      CONFIG_SERVER_URL: http://configserver:9296
      EUREKA_SERVER_ADDRESS: http://serviceregistry:8761/eureka
    ports:
      - "8085:8085"
    networks:
      - ekart-network

volumes:
  mysql_data:

networks:
  ekart-network: